
public class AdventureGUI extends javax.swing.JFrame {
    


    /**
     * Creates new form AdventureGUI
     */
    public AdventureGUI() {
        initComponents();
    }
    public void changeRooms(int room){
        Player.setCurrentRoom(World.rooms[room]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jScrollPane1 = new javax.swing.JScrollPane();
        textDescription = new javax.swing.JTextArea();
        textRoomName = new javax.swing.JTextField();
        jTabbedPaneInput = new javax.swing.JTabbedPane();
        jPanelLook = new javax.swing.JPanel();
        lookButton_0 = new javax.swing.JButton();
        lookButton_1 = new javax.swing.JButton();
        lookButton_2 = new javax.swing.JButton();
        lookButton_3 = new javax.swing.JButton();
        jPanelInventory = new javax.swing.JPanel();
        bagButtonUse_0 = new javax.swing.JButton();
        bagButtonUse_1 = new javax.swing.JButton();
        bagButtonUse_2 = new javax.swing.JButton();
        bagButtonUse_3 = new javax.swing.JButton();
        bagButtonDrop_0 = new javax.swing.JButton();
        bagButtonDrop_1 = new javax.swing.JButton();
        bagButtonDrop_2 = new javax.swing.JButton();
        bagButtonDrop_3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPanelTravel = new javax.swing.JPanel();
        jButtonNorth = new javax.swing.JButton();
        jButtonEast = new javax.swing.JButton();
        jButtonSouth = new javax.swing.JButton();
        jButtonWest = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Adventure Game");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(32, 32, 32));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(400, 400));
        setName("window"); // NOI18N
        setResizable(false);

        textDescription.setEditable(false);
        textDescription.setColumns(20);
        textDescription.setRows(5);
        textDescription.setText(Player.getCurrentRoom().getDescription());
        jScrollPane1.setViewportView(textDescription);

        textRoomName.setEditable(false);
        textRoomName.setText(Player.getCurrentRoom().getName());
        textRoomName.setToolTipText("");
        textRoomName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textRoomNameActionPerformed(evt);
            }
        });

        lookButton_0.setText("jButton1");
        lookButton_0.setEnabled(false);

        lookButton_1.setText("bedroom");
        lookButton_1.setToolTipText("room[0]");
        lookButton_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lookButton_1ActionPerformed(evt);
            }
        });

        lookButton_2.setText("intersection");
        lookButton_2.setToolTipText("room[1]");
        lookButton_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lookButton_2ActionPerformed(evt);
            }
        });

        lookButton_3.setText("jButton4");

        javax.swing.GroupLayout jPanelLookLayout = new javax.swing.GroupLayout(jPanelLook);
        jPanelLook.setLayout(jPanelLookLayout);
        jPanelLookLayout.setHorizontalGroup(
            jPanelLookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLookLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lookButton_0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lookButton_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lookButton_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lookButton_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(275, 275, 275))
        );
        jPanelLookLayout.setVerticalGroup(
            jPanelLookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLookLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lookButton_0)
                    .addComponent(lookButton_1)
                    .addComponent(lookButton_2)
                    .addComponent(lookButton_3))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        jTabbedPaneInput.addTab("Look Around", jPanelLook);

        bagButtonUse_0.setText("jButton5");

        bagButtonUse_1.setText("jButton6");

        bagButtonUse_2.setText("jButton7");

        bagButtonUse_3.setText("jButton8");

        bagButtonDrop_0.setText("jButton9");

        bagButtonDrop_1.setText("jButton10");

        bagButtonDrop_2.setText("jButton11");

        bagButtonDrop_3.setText("jButton12");

        jTextField1.setText("Use an Item:");

        jTextField2.setText("Drop an Item:");

        javax.swing.GroupLayout jPanelInventoryLayout = new javax.swing.GroupLayout(jPanelInventory);
        jPanelInventory.setLayout(jPanelInventoryLayout);
        jPanelInventoryLayout.setHorizontalGroup(
            jPanelInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInventoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInventoryLayout.createSequentialGroup()
                        .addComponent(bagButtonDrop_0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bagButtonDrop_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bagButtonDrop_2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bagButtonDrop_3))
                    .addGroup(jPanelInventoryLayout.createSequentialGroup()
                        .addGroup(jPanelInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bagButtonUse_0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bagButtonUse_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bagButtonUse_2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bagButtonUse_3)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanelInventoryLayout.setVerticalGroup(
            jPanelInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInventoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bagButtonUse_0)
                    .addComponent(bagButtonUse_1)
                    .addComponent(bagButtonUse_2)
                    .addComponent(bagButtonUse_3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bagButtonDrop_2)
                    .addComponent(bagButtonDrop_1)
                    .addComponent(bagButtonDrop_3)
                    .addComponent(bagButtonDrop_0))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jTabbedPaneInput.addTab("Inventory", jPanelInventory);

        jButtonNorth.setText("North");
        jButtonNorth.setMaximumSize(new java.awt.Dimension(50, 100));
        jButtonNorth.setMinimumSize(null);

        jButtonEast.setText("East");
        jButtonEast.setMaximumSize(new java.awt.Dimension(50, 100));
        jButtonEast.setMinimumSize(null);

        jButtonSouth.setText("South");
        jButtonSouth.setEnabled(false);
        jButtonSouth.setMaximumSize(new java.awt.Dimension(50, 100));
        jButtonSouth.setMinimumSize(null);

        jButtonWest.setText("West");
        jButtonWest.setEnabled(false);
        jButtonWest.setMaximumSize(new java.awt.Dimension(50, 100));
        jButtonWest.setMinimumSize(null);
        jButtonWest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTravelLayout = new javax.swing.GroupLayout(jPanelTravel);
        jPanelTravel.setLayout(jPanelTravelLayout);
        jPanelTravelLayout.setHorizontalGroup(
            jPanelTravelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTravelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanelTravelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTravelLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanelTravelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSouth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonNorth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelTravelLayout.createSequentialGroup()
                        .addComponent(jButtonWest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jButtonEast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        jPanelTravelLayout.setVerticalGroup(
            jPanelTravelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTravelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButtonNorth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTravelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonWest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSouth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPaneInput.addTab("Travel", jPanelTravel);

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitButton)
                .addContainerGap(387, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitButton)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        jTabbedPaneInput.addTab("Utility", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textRoomName)
                    .addComponent(jScrollPane1)
                    .addComponent(jTabbedPaneInput, javax.swing.GroupLayout.PREFERRED_SIZE, 453, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textRoomName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPaneInput)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void textRoomNameActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void lookButton_1ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        changeRooms(0);
    }                                            

    private void lookButton_2ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        changeRooms(1);
    }                                            

    private void jButtonWestActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        System.exit(0);
    }                                          

    private void setRoomButtonNames(javax.swing.JButton button, int i){
        
            //button.setText();
    }
    private void updateGUI(){
        textRoomName.setText(Player.currentRoom.getName());
        textRoomName.setToolTipText(Player.currentRoom.getDescription());
        //sets all exit names
        setRoomButtonNames(jButtonNorth, 0);
        setRoomButtonNames(jButtonWest, 1);
        setRoomButtonNames(jButtonEast, 2);
        setRoomButtonNames(jButtonSouth, 3);
    }
    
    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify                     
    private javax.swing.JButton bagButtonDrop_0;
    private javax.swing.JButton bagButtonDrop_1;
    private javax.swing.JButton bagButtonDrop_2;
    private javax.swing.JButton bagButtonDrop_3;
    private javax.swing.JButton bagButtonUse_0;
    private javax.swing.JButton bagButtonUse_1;
    private javax.swing.JButton bagButtonUse_2;
    private javax.swing.JButton bagButtonUse_3;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton jButtonEast;
    private javax.swing.JButton jButtonNorth;
    private javax.swing.JButton jButtonSouth;
    private javax.swing.JButton jButtonWest;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelInventory;
    private javax.swing.JPanel jPanelLook;
    private javax.swing.JPanel jPanelTravel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTabbedPane jTabbedPaneInput;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton lookButton_0;
    private javax.swing.JButton lookButton_1;
    private javax.swing.JButton lookButton_2;
    private javax.swing.JButton lookButton_3;
    private javax.swing.JTextArea textDescription;
    private javax.swing.JTextField textRoomName;
    // End of variables declaration                   
}
